name: deploy-staging

on:
  push:
    tags:
      - "stag-*"

jobs:
  wait-on-build:
    name: wait on build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.ref }}
          check-name: build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
  make-sentry-release:
    name: make sentry release
    runs-on: ubuntu-latest
    needs: wait-on-build
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ultrasoundmoney
          SENTRY_PROJECT: ultrasoundmoney
        with:
          environment: stag
  deploy-serve-frontend:
    name: deploy serve-frontend
    runs-on: ubuntu-latest
    needs: wait-on-build
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: set image deployment/serve-frontend serve-frontend=rg.fr-par.scw.cloud/ultrasoundmoney/frontend:${{ steps.vars.outputs.sha_short }}
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA_STAG }}
          command: rollout status deployment/serve-frontend
